### ISSUE TITLE
Blog Formatting

### ISSUE THREAD

**Issue by MikeInnes** [JuliaLang/www.julialang.org#102]
Has come out pretty badly, [e.g.](https://julialang.org/blog/2017/12/ml&pl).

A bunch of these posts still get a lot of views, so it'd be worth having them look nice.

**Comment by mbauman** [comment]
We just need to move some of the CSS from the old 
[css/screen.css](https://github.com/JuliaLang/www.julialang.org/blob/master/css/screen.css) (which is no longer included) to the new [v2/css/app.css](https://github.com/JuliaLang/www.julialang.org/blob/master/v2/css/app.css).   Let's also delete the old one once we make that transition because it's confusing to folks who don't know which is the right one :)

**Comment by ViralBShah** [comment]
We need a PR.

**Comment by jekbradbury** [comment]
We also need `syntax.css` I think?
