### ISSUE TITLE
Update SciML GSoC projects

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1140]
Hey @ChrisRackauckas please let me know if you will be applying with SciML for GSoC this year so we can figure out what to do with: https://julialang.org/jsoc/gsoc/sciml/

**Comment by logankilpatrick** [comment]
Same with these ones: https://julialang.org/jsoc/gsoc/diffeq/

**Comment by aviks** [comment]
Yeah, I came here to say that there are two separate pages, diffeq and sciml. We may want to merge the two?

**Comment by ChrisRackauckas** [comment]
I don't think it makes sense to merge them. They hit different topics and attract different people. I think doing a slow move is also better than forcing it right away, since this is the one that gets the Google hits right now. https://sciml.ai/dev/ is where it moved but it'll take a bit before people start finding that page instead, so I'd hope to leave this all as-is for a year.

**Comment by logankilpatrick** [comment]
@ChrisRackauckas would be ideal to have the projects updated slightly if certain ones were completed and such
