### ISSUE TITLE
Update WebAssembly Projects

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1142]
Hey @Keno we need to get the compiler projects here: https://julialang.org/jsoc/gsoc/wasm/
updated for GSoC 2021 asap.

There are new requirements for the projects found here: https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list including adding an (easy, medium, hard) rating for each project. Please read through that link and updated the projects as needed.

If you are no long able to mentor the project or the project has been completed, please open a PR to remove it. Thank you!

**Comment by aviks** [comment]
@tshort, @vchuravy @fonsp may be interested

**Comment by fonsp** [comment]
Awesome that this is a GSoC project! We at Pluto are definitely SUPER interested, and Pluto+wasm could also contribute back to Julia's popularity:
- you can make articles/webapps running on WASM
- we can host an online Julia IDE similar in spirit to observablehq.com, but with a _real_ scientific language instead of JS

(@keno I am about halfway done with writing a minimal Pluto+wasm demo, I'll keep working on it soon!)

---

We would be happy to co-mentor for:
- integration of JS objects
- DOM integration
- Web-integration packages
- (Pluto) notebook integration (note that the Iodide project has been [discontinued as of Sept 2020](https://github.com/iodide-project/iodide/blob/master/README.md))
- _(possibly others)_

**Comment by AriMKatz** [comment]
This is also connected  to @jpsamaroo 's work on static compilation using small or no runtime and GPUCompiler. A general WASM backend for dev and an option to spit out static WASM for deployment. 

Details here: https://docs.google.com/document/d/1rLpZf-HK6b9uYPDT_piUza4LUhtIrLbUftGa_YaXGKQ/edit?usp=sharing

(Which would make a good GSOC as well. Maybe we can have both work together)

**Comment by logankilpatrick** [comment]
@Keno the proposal and such were not updated so the project has been de-referenced from the project list but feel free to update and add it back in.
