### ISSUE TITLE
Do the benchmarks include compile time? 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1202]
@ViralBShah do these https://julialang.org/benchmarks/ include compile time? Probably best to mention it either way

**Comment by ViralBShah** [comment]
Pretty sure it doesn't. 

https://github.com/JuliaLang/Microbenchmarks/blob/master/perfutil.jl

**Comment by logankilpatrick** [comment]
Got it, perhaps we could re-compile this for 1.6 and see what the impact is.

**Comment by timholy** [comment]
But the benchmarks are very outdated. Example: https://discourse.julialang.org/t/julias-applicable-context-is-getting-narrower-over-time/55042/76?u=tim.holy

**Comment by giordano** [comment]
> Got it, perhaps we could re-compile this for 1.6 and see what the impact is.

It isn't that easy because you need a system with all programs installed.  Some of them are proprietary and require a license.

**Comment by ViralBShah** [comment]
There really will be no change in these benchmarks. They are already close to C speed.

**Comment by timholy** [comment]
I agree with @giordano that it's very nontrivial to rerun these. Perhaps we could ditch proprietary platforms and only run against open-source alternatives? Even then it's of course not easy because it will involve (1) installing a bunch of software (maybe easy, but maybe not) and (2) build fixes like https://github.com/JuliaLang/Microbenchmarks/issues/43.

Still, if someone wants to tackle this, I think it would be valuable. I was pretty surprised in that discourse conversation at how many people think that Julia still isn't as fast as C, and that "within 2x" is still not good enough for many people. I'm not sure these benchmarks are the reason, but they are literally the first text-link on https://julialang.org/.

My impression is that for recent Julia that 2x has mostly turned into 1x, and if true it might bring more of the dots in the Julia column closer to the C line. (Other languages might have made similar progress, of course.)

**Comment by ViralBShah** [comment]
@timholy That's a very good point. We should probably not have that as the first link, and also to @logankilpatrick 's point- can clarify on the benchmarks page that these do not include compile time.

**Comment by ViralBShah** [comment]
This might be a better benchmark page: https://benchmarksgame-team.pages.debian.net/benchmarksgame/which-programs-are-fastest.html

Although I suppose some more benchmark optimization is necessary. @KristofferC was more closely involved with those.

**Comment by timholy** [comment]
That's a useful set of benchmarks. Aside from being good, one advantage it has is apparent neutrality: since we don't control them, there's no risk that we'd be perceived as biasing the results. (I was curious how they take account of Julia's compile-time latency...)

However, the benchmarks are of pretty different character: the ones at "the game" seem oriented towards all-the-stops optimization: SIMD vectorization, multithreading, bounds-check elimination, clever caching, etc. So I think our own microbenchmarks have an important niche: it's probably more useful to a wider set of people to think about "typical" coding vs "extreme" coding.

**Comment by ViralBShah** [comment]
I believe it is because of compile time that we don't do as well as the others. If we had a clear "compile a binary stage" and then "run that binary", we may do even better.

There are other benchmarks that I like to point people to:
1. DataFrames like stuff: https://h2oai.github.io/db-benchmark/
2. Graphs: https://www.timlrx.com/blog/benchmark-of-popular-graph-network-packages-v2
3. CSV: https://github.com/davidanthoff/csv-comparison (may need updating)
