### ISSUE TITLE
Consider integrating something like JuliaBox/Juniper for a code demo

### ISSUE THREAD

**Issue by jekbradbury** [JuliaLang/www.julialang.org#125]
Ines Montani built this https://github.com/ines/juniper for the SpaCy docs recently, and it seems like we could slot a Dockerized Julia kernel in fairly easily. The primary choice would be whether to rely on the public Binder hosting or host it somewhere else; another option is to figure out how to get a mini-JuliaBox environment inline.

**Comment by ViralBShah** [comment]
Maybe repl.it?

**Comment by ViralBShah** [comment]
Maybe @keno 's wasm work is good enough to show some basic syntax (with ample warning that it is extremely limited).

**Comment by logankilpatrick** [comment]
Started looking into this for JuliaAcademy

**Comment by ViralBShah** [comment]
The wasm stuff isn't good for JuliaAcademy. There was discussion about potentially adding Julia to Colab, but unfortunately that seems to have taken a backburner. JuliaBox is perhaps the best option for now, since it does give a 1 month free trial. Probably good enough for a new learner, and by then they really should get a Julia dev environment set up on their computer.

**Comment by logankilpatrick** [comment]
Repl.it is awesome and free if you are part of the GitHub Student Dev Pack!

**Comment by logankilpatrick** [comment]
If anyone has any cool ideas, we could add that to the home page of the site (if people think that's a good idea).

**Comment by logankilpatrick** [comment]
closed via #753
