### ISSUE TITLE
Static html blog post

### ISSUE THREAD

**Issue by weymouth** [JuliaLang/www.julialang.org#1348]
I've written a tutorial that might be fun to host on the JuliaLang blog. I made it using Pluto and have exported the static HTML which can be found [here.](https://github.com/weymouth/weymouth.github.io/blob/master/Shark.jl.html).

@ViralBShah

**Comment by ViralBShah** [comment]
@tlienart Any suggestions on how we convert the Pluto HTML posted above into a blog post? Would it be possible to just take the standard blog template and then dump the static html below?

**Comment by tlienart** [comment]
oh wow, that's a bit of a mammoth page...

it's possible to do this but currently requires manual work; there may be a future where Pluto notebooks can be directly plugged in Franklin following the example that Fons did for the intro to computing site but for now it's not there.

What might work is to:

- take the page as it stands and
- remove the top part until the script loading `lodash`
- remove the bottom from `</head>` to the end
- put the content of that in a `.md` file with

```
+++
title = "the title"
# other variables, follow template from other blog posts
+++
~~~
<script src="https://cdn.jsdelivr.net/npm/lodash@4.17.20/lodash.min.js" defer></script>
<script src="https://cdn.jsdelivr.net/npm/@observablehq/stdlib@3.3.1/dist/stdlib.js" defer></script>
...
<script src="https://cdn.jsdelivr.net/gh/fonsp/Pluto.jl@0.15.1/frontend/editor.js" type="module" defer></script>
    <script src="https://cdn.jsdelivr.net/gh/fonsp/Pluto.jl@0.15.1/frontend/warn_old_browsers.js"></script>

    <script src="https://cdn.jsdelivr.net/gh/fonsp/Pluto.jl@0.15.1/frontend/common/SetupMathJax.js"></script>
    <script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3.1.2/es5/tex-svg-full.js" async></script>
~~~
```

very likely it will not look good because there will be clashes between the layout of the site and the layout that Pluto tries to apply same with the CSS, but would be good to test this as a first step and see what it gives.

**Note**: my suggestion for now would be to either (1) wait until there's a more streamlined support for Pluto notebooks in Franklin (not soon but eventually) or (2) use `Literate.jl` to transform the notebook into a Literate file, and then use that (since Franklin directly supports Literate files).

**Comment by weymouth** [comment]
Yeah, it's big because of the embedded gifs. 

I'm happy to try out 2. What is the output from Literate that you need?

**Comment by tlienart** [comment]
If you transform your Pluto file into a `.jl` file that Literate can understand and that I can run directly on my side, I can do the rest (including saving gifs in the right location and loading them so don't worry about that)

**Comment by tlienart** [comment]
PS: there won't be sliders, but they also don't work on http://weymouth.github.io/Shark.jl.html as far as I can see so you're probably fine with this?

**Comment by weymouth** [comment]
Ok. I'll give it a shot.

**Comment by tlienart** [comment]
I think the downloadable `notebook.jl` file is pretty close to what I need with a few things

- remove the interactiveutils stuff
- remove the manifest at the bottom
- remove all the `begin-end` stuff
- remove the Pluto timestamp thingy
- turn all text into comment (`# ...`)

and that should be roughly enough

**Comment by ViralBShah** [comment]
@fonsp may be interested in this discussion as well.

**Comment by weymouth** [comment]
Ok. I've tried to do as suggested and put it [here](https://github.com/weymouth/weymouth.github.io/blob/master/Shark_cleaned.jl). 

I'm not sure how it's going to look. Code blocks have comments, which now look the same as the markdown blocks... Let me know.

**Comment by StefanKarpinski** [comment]
This blog post is awesome.

**Comment by weymouth** [comment]
Thanks!

**Comment by fonsp** [comment]
I wont be able to look into this until next month, but the solution from the mit course was:
- (if you want to automate the HTML generation) use PlutoSliderServer.jl as demonstrated in https://github.com/JuliaPluto/static-export-template
- use an iframe to show a pluto notebook inside a page with additional navigation elements. use CSS media queries to show the iframe at 100vh 100vw on small screens

hope it's useful!
