### ISSUE TITLE
PR Previews fail to load

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#1472]
The previews through Netlify are still failing to load

**Comment by logankilpatrick** [comment]
Cc @DilumAluthge @tlienart

**Comment by DilumAluthge** [comment]
It looks like it's pushing to the `gh-previews` branch correctly. Maybe the issue is with Netlify?

Who has access to the Netlify account? I do not.

**Comment by tlienart** [comment]
As I mentioned in the blogpost PR from a few weeks ago, I *think* the Netlify account that was being used for the preview was mine for some reason; I don't use my Netlify account and so was not aware of what was going on there. Recently they seem to have added some stuff where you're forced to add a credit card and previews are not free, since I obviously did none of this, my Netlify account is blocked and so assuming the previews were built via my account that would be a reason why they're not built anymore.

An approach that does not require Netlify would be to use another GH repo e.g. `julialang_website_previews` and have PRs commit to that other repo which would generate a site for each commit. I think that's doable though there would need to be some thought into doing this because different PRs would amount to clashing histories. 

For now any PR should be tested by having the person about to do the merge explicitly doing a `serve()` locally and reporting a screenshot of the new page working.

**Comment by DilumAluthge** [comment]
@ViralBShah @logankilpatrick Can we get a free Netlify account for Julia to use for the previews?

**Comment by logankilpatrick** [comment]
Fixed this
