### ISSUE TITLE
Adding Newsletter to Julia Language Blog

### ISSUE THREAD

**Issue by rayegun** [JuliaLang/www.julialang.org#2148]
@Krastanov some of us have been talking about potentially adding your monthly newsletter as a blogpost to the Julia Language Blog.

Is that something you'd be interested in? I don't think it would involve too much additional effort from you. We'd probably like the blog PR to be made 1-2 days before the actual newsletter is posted to give us time to edit it. But otherwiseI think it's a good idea. 

Of course we'd still post the same post or link to the blog on Discourse each month for people to comment on etc.

What are your thoughts? Also anybody else paying attention to this repo what are your thoughts? Our goal is to keep the blog low noise, so no more than 2-3 posts per month at peak. But currently there are vanishingly few posts throughout the year, and this is one way to encourage community growth and advertise packages to the world.

**Comment by Krastanov** [comment]
Sounds good to me! The only constraint is that on months when I am busy the discourse post is posted pretty late and somewhat hastily. E.g. instead of posting the September letter on September 30th, it might be on October 5th, and then the extra two days of review would make that more like October 7th.

As long as everyone is still fine with this "best effort" type of unreliable timing on my end, I am fine with the setup you suggested.

**Comment by rayegun** [comment]
I don't think there's any problem with that! You're doing an immense amount of volunteer legwork on these newsletters so whatever cadence you need is perfect.

If we're all set then I'll close this issue and look forward to a PR for the next newsletter! I think we'll plan to leave them as PRs for 48 hours to allow people to propose adding content (I especially will probably add blurbs about JuliaCon deadlines) and then post it!
