### ISSUE TITLE
Add that a choco installation is also available for julia

### ISSUE THREAD

**Issue by musm** [JuliaLang/www.julialang.org#348]
On windows a chocolatey installation is available through
`choco install julia`
which makes installing and maintaining the latest version of julia easy for those who already have choco and use it. 

see https://chocolatey.org/packages/Julia

**Comment by ararslan** [comment]
Do you know whether it uses the official binaries? (The easiest way to check is to install it and check the REPL banner.) If so, +1 to mentioning it. Otherwise I don't think we should encourage installing third-party builds of Julia which may be using system libraries or otherwise not carrying our necessary patches.

**Comment by musm** [comment]
It is in fact using the official binaries provided by the jula lang organization.
`choco` packages are just simple wrappers of the official installers.

**Comment by ararslan** [comment]
Awesome!

**Comment by ViralBShah** [comment]
Submit a PR?

**Comment by musm** [comment]
Sure but where on  https://julialang.org/downloads/  should this be put

**Comment by ViralBShah** [comment]
The right place where all the other distribution instructions are: https://julialang.org/downloads/platform.html

**Comment by musm** [comment]
Thanks. I feel like that page should be more discoverable. It was hard to find where exactly that information is located on the main download page.
