### ISSUE TITLE
Strange layout on mobile browsers

### ISSUE THREAD

**Issue by lostella** [JuliaLang/www.julialang.org#409]
The website renders strangely on iOS 12.3.1 (I’ve tried on Firefox and Safari). After the homepage loads, zooming out yields the following:

![6300A3D8-D69E-42C1-A101-EA71AB517187](https://user-images.githubusercontent.com/433963/61578172-2077ae80-aaf3-11e9-80a2-8c88ebf74413.png)

**Comment by tpapp** [comment]
I cannot reproduce on Android, with Chrome (76.0.3809.89) and Firefox (68.1).

There are sites which offer multi-browser testing, some with a free tier, that could be useful for reproducing this.

**Comment by nicknack23** [comment]
I’m pretty sure the problem is the width of the iframe that contains the Juliacon videos. Here’s a 20 second clip that uses the cool mobile browser emulation feature in desktop Chrome (“toggle device toolbar”) and Firefox (“responsive design mode”) to demonstrate the issue:

https://imgur.com/a/KAZBLyS

Sorry that it’s so blurry. I wanted to test imgur’s new video clip capability but apparently their reencoding is really aggressive.

**Comment by niclasmattsson** [comment]
I’m pretty sure the problem is the width of the iframe that contains the Juliacon videos. Here’s a 20 second clip that uses the cool mobile browser emulation feature in desktop Chrome (“toggle device toolbar”) and Firefox (“responsive design mode”) to demonstrate the issue:

https://imgur.com/a/KAZBLyS

Sorry that it’s so blurry. I wanted to test imgur’s new video clip capability but apparently their reencoding is really aggressive.

**Comment by ViralBShah** [comment]
The issue is certainly the youtube video. Is there a way for it to serve a smaller one for mobiles automatically?

**Comment by abhishalya** [comment]
This can be fixed easily with Hugo built youtube shortcode.

**Comment by lostella** [comment]
I’m not sure that will work, since the video is randomly picked from a list with some javascript, currently.

Maybe some proper css for the iframe containing the video is required in this case.

**Comment by ViralBShah** [comment]
I assume we can still run the custom js to pick a random video, but then feed it to the hugo youtube shortcode for display.

**Comment by lostella** [comment]
I don't have much experience with Hugo, but my understanding is that shortcodes are evaluated statically at generation time, so I'm not sure how that could be done.
