### ISSUE TITLE
Ecosystem tabs resize the view

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#55]
@essenciary How do we prevent the different ecosystem tabs on the homepage from resizing the view there as we switch from one to the other?

**Comment by essenciary** [comment]
It's because the height of the tab grows to accommodate the content. We can: 

1 - scale all tabs to the height of the tallest tab? 
2 - have a fixed height and scroll the content (I advise against this, it's a usability issue, especially aweful on tablets). 

For 1, we could have a css property of "min-height" - and then, when the content editors change the tabs copy, update the css var accordingly, to reflect the new content. Or, try it with some JavaScript (measure the height of each tab, and resize all tabs to match the tallest).
