### ISSUE TITLE
Buttons on banner do not align nicely

### ISSUE THREAD

**Issue by goggle** [JuliaLang/www.julialang.org#592]
The banner on the homepage currently looks like this:
![image](https://user-images.githubusercontent.com/1856425/72569211-24c23000-38ba-11ea-9aea-329445c0fe3b.png)

I'm not a design expert, but the alignment of the three buttons looks wrong to me.
I would suggest to remove the github button from the banner (and maybe put it somewhere else on the homepage) and align the two colored buttons in the center below "The Julia Programming Language".

**Comment by logankilpatrick** [comment]
Agreed, will have to look into this.

**Comment by cormullion** [comment]
typo: “clsss” perhaps?

https://github.com/JuliaLang/www.julialang.org/blob/936034ad46bcd85549754e671b04eba094dd134c/layouts/partials/jumbotron.html#L30

**Comment by goggle** [comment]
@cormullion I don't think that's the cause of the issue, but thanks for reporting this, it seems to be already fixed.

**Comment by goggle** [comment]
@ViralBShah Why did you close this? I think that typo was **not** the cause of this issue. The layout of the banner hasn't changed (at least not for me).

**Comment by ViralBShah** [comment]
@goggle Sorry I misread your message thinking "seems to be already fixed" referred to this issue and not just the misspelling.

**Comment by cormullion** [comment]
This typo isn't currently fixed. (It was fixed in (https://github.com/JuliaLang/www.julialang.org/commit/70cea6053969afe1d49c1f33a5d605e652d06a1a) then it was unfixed by https://github.com/JuliaLang/www.julialang.org/commit/6dd0ed3ae1df0ec94cd2808a6a42666a375bf9ff) .

I don't know if fixing the typo will fix the issue. Logan has confused me... :)
