### ISSUE TITLE
Simplify the download page so it's less intimidating 

### ISSUE THREAD

**Issue by musm** [JuliaLang/www.julialang.org#658]
- The download page is too intimidating for newcomers. Going to the download page you are hit with a complex wall of text and confusing matrices of downloads configurations.

![image](https://user-images.githubusercontent.com/4319522/76653703-98da2680-653f-11ea-9feb-e304bb9fa934.png)

----

- Let's simplify things for the first half of the page. We can keep the granular matrix of downloads further down the page, but users should be greeted with a simple download page that is not complicated.

- We should aspire to the following example

![image](https://user-images.githubusercontent.com/4319522/76653690-91b31880-653f-11ea-9dd9-02cdc5c14066.png)

@logankilpatrick

**Comment by cormullion** [comment]
I just made this using a grid:

<img width="887" alt="Screenshot 2020-03-19 at 18 17 29" src="https://user-images.githubusercontent.com/52289/77100904-4cdf2400-6a0e-11ea-8475-88bec4a6f348.png">

Sort of thing? The [help] could be a question mark I suppose...

**Comment by tlienart** [comment]
Nice, maybe a  one click button for the standard option would be good? (if we're going with something similar to VS Code). I guess that button could wrap the symbol so that if you click on it you get the most recent stable release that is most likely to  correspond to  your platform. 

Personal preference would also be for the icons to be smaller, maybe 70% of the size you show 😄

**Comment by musm** [comment]
Yeah Looks good, but the icons are kinda massive and their not all the same size. Is there a better linux photo? It's weird seeing a B&W penguin :) 

For the windows one can we use a B&W or color version like this: 
![image](https://user-images.githubusercontent.com/4319522/77102256-eac2f680-69ee-11ea-89ed-db547ab20401.png)

**Comment by fredrikekre** [comment]
Can we just detect the running system and present just a single button? I know that is done for other projects.

**Comment by musm** [comment]
I don't think we should present a single button because there have been several times when I've wanted to download e.g. linux binaries for WSL. Having them all present makes it very user friendly to quickly grab and test the binaries you want.

**Comment by fredrikekre** [comment]
I mean obviously the other ones shouldn't be hidden, but we can present a main one. The regular user probably wants that one.

Here is an example: https://ngrok.com/download

**Comment by cormullion** [comment]
I avoided color just because it would be a bit inconsistent- with some in color and others not. (I didn't bother to size everything accurately at this stage... :))

**Comment by musm** [comment]
Here's a mono linux logo that looks much better

 

![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Tux_Mono.svg/848px-Tux_Mono.svg.png)

**Comment by musm** [comment]
I would also move the (.exe) and (.dmg) down to the links, since we are also planning to provide (.zip)  for Windows. 

I would then move `(help)` next to the OS.

**Comment by ViralBShah** [comment]
The `help` should probably called `Installation notes` or something. They are probably not needed by most users - so I would personally move them to the end of the table in their own row.

**Comment by ViralBShah** [comment]
The installation notes could also just be moved to the Julia manual.

**Comment by ViralBShah** [comment]
I also like detecting the default platform and offering that `ngrok` like install and run instructions. Can be a separate PR if we ever get there.

**Comment by hug0b** [comment]
Some initial wireframes I made for a modernized download section, please tell me what you think. 
I tried to match the bootstrap style and existing designs.

"Upcoming releases" section is kept separate for now because it has additional description text new users probably don't care about.
"Help" has become "Installation instructions".

![1 - idle](https://user-images.githubusercontent.com/18407984/180891998-d5b8f8a9-413f-41e7-b3c1-999a9fb117a1.png)

The download button starts download of default recommended version (stable 64 bit).
![2-btn-active](https://user-images.githubusercontent.com/18407984/180892001-7c98ae9c-0670-4f8d-bce8-13f2958c172b.png)

Clicking the dropdown section of the button reveals more download options.
![3-dropdown-active](https://user-images.githubusercontent.com/18407984/180892002-3e9a2e29-c854-4542-8bca-656f879cb97c.png)

Inspirations:
https://ngrok.com/download
https://www.jetbrains.com/idea/download/
https://nodejs.org/en/download/current/

**Comment by fredrikekre** [comment]
I think that looks great!

**Comment by ViralBShah** [comment]
Looks great. How will the platforms be shown?

**Comment by giordano** [comment]
Can maybe have a button for the platform (trying to guess the correct one) and another one for the versions (filtering with some javascript magic those available for the chosen platform)?  This could simplify #1706.

**Comment by hug0b** [comment]
> Looks great. How will the platforms be shown?

Same design but navigating through each tab would change the download button link and dropdown.

> Can maybe have a button for the platform (trying to guess the correct one) and another one for the versions (filtering with some javascript magic those available for the chosen platform)? This could simplify #1706.

I guess the whole page needs to be redesigned and maybe broken down into multiple pages (like maybe a simple download page for most user needs which then shows a link to a page with all other releases nightly, older, 32bit etc.) 
I'm not to sure what would be best and I'm not too happy with my design tbh.

**Comment by tripathi-genius** [comment]
How to contribute?
