### ISSUE TITLE
Adding a Calendar for Julia events

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#685]
Thoughts on adding some sort of calendar in the community section where we can have a global list of Julia events? 

The use case would be I am bored right now and want to see if there's any IRL/live things going on in the Julia world.

**Comment by abhishalya** [comment]
We can add Google Calendar, it can be easily integrated and we won't have to make changes to the site as well. It works nicely, but someone would have to regularly update the calendar

**Comment by ViralBShah** [comment]
The problem is keeping it maintained and updated. It's a bit of a commitment going forward, but a great idea if we can do that.

**Comment by tlienart** [comment]
A calendar could be quite annoying (especially tied to google) because you have to sign up, and then it pollutes your own calendar, and then you end up removing it. 
Maybe easier would be to have a "News" section with an RSS feed where things like releases, new blog pots and events are announced; (Franklin supports RSS generation fwiw).

**Comment by abhishalya** [comment]
@tlienart Not really, like we have this on [coala site](https://coala.io/#/getinvolved), not sure where sign up comes here. I guess its only when you want to add that calendar to yours. Also, probably the best thing about having Google account is that whoever is updating the calendar won't have to make changes here on site. He can just add it anywhere on Google Calendar and it would be automatically reflected here.

As from the issue I understood that the user only wants to know if there is any event right now. Not necessarily that he wants to get all updates later on.

**Comment by tlienart** [comment]
fair enough, I think I would still be in favour of a News section if only because it allows a user to scroll through past event and see that there are regular things happening but 🤷‍♂ (and, I'm not going to hide it, I don't like the google calendar, its look & the fact that it's yet another google service but this shouldn't come into consideration)
