### ISSUE TITLE
Tiny Julia logo resizing issue

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#69]
https://twitter.com/hrdwrknvrstps/status/1025442923180175360

**Comment by ViralBShah** [comment]
@essenciary Would be good to fix this one. Happens for me too.

**Comment by essenciary** [comment]
Pushed fix

**Comment by Keno** [comment]
<img width="564" alt="screen shot 2019-01-04 at 6 07 07 pm" src="https://user-images.githubusercontent.com/1291671/50859405-44e31900-1361-11e9-8c66-77500cbcba88.png">

I still see this

**Comment by Keno** [comment]
![screen shot 2019-01-08 at 4 20 01 pm](https://user-images.githubusercontent.com/1291671/50859421-54626200-1361-11e9-9a53-4eb02123fe69.png)

I still see this

**Comment by essenciary** [comment]
Hmmm, odd, it was properly fixed for sure. OK, lmk.

**Comment by ViralBShah** [comment]
Actually, I decided against changing the menu. Is it possible to fix this?

**Comment by essenciary** [comment]
@ViralBShah ok, I figured out what it was, cause I _knew_ I fixed it. It's because of the GSoC extra menu item. Basically now the menu doesn't fit on smaller screens. So yeah, there's no room for everything. If I keep the size of the logo, it looks like this: 

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/11292378/52068439-f5b59000-257c-11e9-9499-f8550caa2713.png">

**Comment by ViralBShah** [comment]
It just occurred to me yesterday that it was most likely due to the GSoC. Would reducing the logo size help?

**Comment by essenciary** [comment]
Indeed, it was the GSoC item. I commented in the other issue (one video). I tweaked it a bit so for smaller resolutions, both the spacing between menu items and the logo become smaller. Looks good now.
