### ISSUE TITLE
Add contributing section

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/www.julialang.org#760]
This will help get new people involved

**Comment by zdroid** [comment]
Is https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md content sufficient?

**Comment by logankilpatrick** [comment]
I envision that plus some of the core aspects of this: https://devguide.python.org

**Comment by ViralBShah** [comment]
Is this relevant for GSOD?

**Comment by HarshCasper** [comment]
Hello @logankilpatrick @ViralBShah 

Thanks for making this Issue as `good first issue`. I would like to work on this by taking inspiration from the [JuliaLang Contribution File](https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md) including some pointers from the [Python Dev Guide](https://devguide.python.org/). 

Kindly assign me this or give me a go ahead so that I can bring up a draft and get a review on the same before I make a PR 😄

**Comment by ViralBShah** [comment]
#1328 has some concrete ideas, and the CONTRIBUTING.md document is updated from time to time.
